//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoursesApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class_Room_Comments
    {
        public int Class_Room_Comment_Id { get; set; }
        public string Comment { get; set; }
        public System.DateTime Commen_Date { get; set; }
        public Nullable<int> Student_Id { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
