//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoursesApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_Questions
    {
        public int Question_Id { get; set; }
        public string Title { get; set; }
        public string Question_Content { get; set; }
        public int Course_Id { get; set; }
        public int Question_Type_Id { get; set; }
    
        public virtual Course_Question_Types Course_Question_Types { get; set; }
        public virtual Cours Cours { get; set; }
    }
}
