//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoursesApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question_Answers
    {
        public int Answer_Id { get; set; }
        public string Answer { get; set; }
        public System.DateTime Answer_Date { get; set; }
        public int Student_Id { get; set; }
        public int Question_Id { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
